quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/postgres
quarkus.datasource.jdbc.driver=org.postgresql.Driver

milvus.uri=http://localhost:19530
milvus.collection.name=demo_ai_documents

quarkus.langchain4j.openai.gemma.base-url=http://localhost:1144/v1
quarkus.langchain4j.openai.chat-model.model-name=gemma
quarkus.langchain4j.chat-model.provider=openai

quarkus.langchain4j.openai.granite.base-url=http://localhost:1145/v1
quarkus.langchain4j.openai.embedding-model.model-name=granite
quarkus.langchain4j.embedding-model.provider=openai

quarkus.langchain4j.milvus.host=localhost
quarkus.langchain4j.milvus.port=19530
quarkus.langchain4j.milvus.create-collection=false
quarkus.langchain4j.milvus.collection-name=demo_ai_documents
# These two setting are not supported by the current version of Quarkus Langchain4j extension
# Also field with text cannot be overriden and is default text
quarkus.langchain4j.milvus.primary-field=id
quarkus.langchain4j.milvus.vector-field=vector


quarkus.banner.enabled=false